def printMeniu():
    print("Please choose one command from below:")
    print("FOR STUDENTS:")
    print("\t1)add <studentID> <studentName> <studentGroup>: if you want to add a new student")
    print("\t2)remove student <studentID>: if you want to remove a student")
    print("\t3)update student <studentID> <studentGroup>: if you want to update a student's group ")
    print("\t4)list students: if you want to list all the students")
    print('\n')
    print("FOR ASSIGNMENTS:")
    print("\t1)add <assignmentID> description <assignmentDescription> deadline <assignmentDeadline>: if\nyou want to add a new assignment. The deadline will have the following format: DD/MM")
    print("\t2)remove assignment <assignmentID>: if you want to remove an assignment")
    print("\t3)update assignment <assignmentID> description <assignmentDescription> deadline <assignmnetDeadline>: if\nyou want to update an assignment. EX: update assignment 123 description None deadline 12.09, if you want to modify only the deadline")
    print("\t4)list assignments: if you want to list the assignments ")
    print('\n')
    print("FOR GRADES:")
    print("\t1)grade <grade> to student <studentID> for <assignmentID>: to grade a student")
    print("\t2)list grades: to list all the grades")
    print('\n')
    print("FOR ASSIGNING ASSIGNMENTS:")
    print("\t1)student <studentID> assignment <assignmentID>:- if you want to give a student an assignment")
    print("\t2)group <group number> assignment <assignmentID>:-if you want to give to an entire group the same assignment")
    print('\n')
    print("FOR STATISTICS:")
    print("\t1)stat assignment <assignmentID> alpha :if you want all students who received a given assignment, ordered alphabetically") 
    print("\t2)stat assignment <assignmentID> avg : if you want all students who received a given assignment, ordered\n by average grade at that assignment")  
    print("\t3)late :if you want all students who are late in handing in at least one assignment. These are all the\n students who have an ungraded assignment for which the deadline has passed. ")
    print("\t4)top :if you want the students with the best school situation, sorted in descending order of the average\n grade received for all assignments.")
    print("\t5)all :if you want all assignments for which there is at least one grade, sorted in descending order of\n the average grade received by all students who received that assignment.")
    print('\n')
    print('undo-if you want to undo the previous operation made')
    print('redo-if you want to redo')
    print("x-if you want to exit")
